FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y wget

RUN wget https://deb.nodesource.com/setup_18.x -O setup.sh

RUN bash setup.sh

RUN apt-get install -y nodejs

COPY ./site-setup.sh /site-setup.sh

COPY ./jokeGenerator /jokeGenerator
RUN chmod +x /site-setup.sh

ENTRYPOINT [ "./site-setup.sh" ]